### PR TITLE
[tuya] Improve decode color format error handling

### LINKED ISSUE #540: [tuya] IllegalArgumentException: Unknown color format
The color data point for one of my Tuya lighting devices get initialized to some weird value `H^K` whenever it is restarted. This is causing an `IllegalArgumentException` error preventing the relevant Thing from going online. The only workaround is to log into my Tuya Smart app and change the color to update the data point. No command can be sent on the OH side since the relevant Thing is offline.

Wouldn't it be better to just set the state of the relevant channel to `UnDefType.UNDEF` in that case?

I am using the `4.1-SNAPSHOT` version.

```
2023-12-20 17:04:14.304 [TRACE] [a.internal.handler.TuyaDeviceHandler] - 'tuya:tuyaDevice:xxxxxxxx' received status message '{20=true, 21=white, 22=500.0, 23=500.0, 24=H^K, 25=200000000200000000000003e80000, 26=0.0}'
2023-12-20 17:04:14.304 [WARN ] [rnal.local.handlers.UserEventHandler] - xxxxxxxx/xx.xx.xx.xx:xx: class java.lang.IllegalArgumentException caught, closing the channel
java.lang.IllegalArgumentException: Unknown color format
        at org.smarthomej.binding.tuya.internal.util.ConversionUtil.hexColorDecode(ConversionUtil.java:60) ~[?:?]
        at org.smarthomej.binding.tuya.internal.handler.TuyaDeviceHandler.processChannelStatus(TuyaDeviceHandler.java:168) ~[?:?]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
        at org.smarthomej.binding.tuya.internal.handler.TuyaDeviceHandler.processDeviceStatus(TuyaDeviceHandler.java:144) ~[?:?]
        at org.smarthomej.binding.tuya.internal.local.handlers.TuyaMessageHandler.channelRead(TuyaMessageHandler.java:81) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [bundleFile:4.1.99.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [bundleFile:4.1.99.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [bundleFile:4.1.99.Final]
        at org.smarthomej.binding.tuya.internal.local.handlers.HeartbeatHandler.channelRead(HeartbeatHandler.java:90) [bundleFile:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [bundleFile:4.1.99.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [bundleFile:4.1.99.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [bundleFile:4.1.99.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) [bundleFile:4.1.99.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) [bundleFile:4.1.99.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [bundleFile:4.1.99.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [bundleFile:4.1.99.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [bundleFile:4.1.99.Final]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [bundleFile:4.1.99.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [bundleFile:4.1.99.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [bundleFile:4.1.99.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [bundleFile:4.1.99.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [bundleFile:4.1.99.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) [bundleFile:4.1.99.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [bundleFile:4.1.99.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [bundleFile:4.1.99.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [bundleFile:4.1.99.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) [bundleFile:4.1.99.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) [bundleFile:4.1.99.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) [bundleFile:4.1.99.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) [bundleFile:4.1.99.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [bundleFile:4.1.99.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [bundleFile:4.1.99.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [bundleFile:4.1.99.Final]
        at java.lang.Thread.run(Thread.java:840) [?:?]
```

### PR DESCRIPTION
**Pull request by jsetton**
Fixes #540

### CODE REVIEW

**Comment by J-N-K** [comment]
I would suggest a different solution, that also covers illegal formats for other value: Surround l. 166 to l. 193 with 

```
try {

...

} catch (IllegalArgumentException ignored) {
}
updateState(channelId, UndefType.UNDEF);
```

And keep the log we have now. WDYT?

**Comment by jsetton** [comment]
What about handling `Integer.parseInt` exception? I also personally rather have a try statement in a utility function than clogging the handler function or at the very least only cover the statements that would generate the catch exception.

As far as setting the channel to `UNDEF`, I don't mind doing it at that the bottom for any channel that wasn't updated but I have some reservation about the existing log line. In the use case I covered, I don't think it should log a warning since I always get this issue when my device is restarted and there isn't much that can be done to fix this. However it should certainly log a warning if it's an unknown data point.

**Comment by J-N-K** [comment]
I agree, but it sure is garbage. We can't know if it is a single "initial value" or we received an invalid value later, so I guess a warning is fine.

We usually try to return definite values and not `null`, it makes life much easier if it becomes a little bit more complex than here. That's why the method throws an exception instead of returning `null`. If it was Kotlin and we could use a safe-call or elvis operator I would agree that returning `null` is preferred.

I agree that we should use `(IllegalArgumentException | NumberFormatException ignored)` to also catch that one.

**Comment by jsetton** [comment]
I made the changes per your comments. I forgot that `NumberFormatException` extends from `IllegalArgumentException`. So it is not needed.

**Review by J-N-K — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
